version: '3.3'

services:

  db:
    image: mysql
    env_file:
      - .env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080
